lr:
    - 0.001
    - 0.0001
l2:
    - 1.0
    - 0.1
    - 0.01
dropout:
    - 0.5
    - 0.2
heads:
    - 4
    - 8
lambda:
    - 5.0
    - 2.0
    - 1.0
    - 0.5
    - 0.1
    - 0.01
epochs: 10000
latent_dim: 128
