# config.yaml
# Base configuration
p: 113
lamb: 2
latent_dim: 128
depth: 1
heads: 4
epochs: 20000
lr: 1e-3
l2: 1.0
dropout: 0.5
train_frac: 0.5

# Search space
search_space:
  latent_dim: [128, 256]
  train_frac: [0.3, 0.5]
  lamb: [0.0, 0.5, 2]
  l2: [0.1, 1.0]
  heads: [4, 8]
  depth: [1, 2]
