# config.yaml
default:
    p: 113
    depth: 1
    epochs: 50_000
    latent_dim: 128
    lr: 0.0003
    train_frac: 0.5
    heads: 4
    dropout: 0.1
    lamb: 0.5
    l2: 0.33

search_space:
    lr: [0.0001, 0.0003, 0.001]
    l2: [0.1, 0.5, 1.0]
    alpha: [0.8, 0.95, 0.99]
    lamb: [0.1, 0.4, 2.0]
    dropout: [0.1, 0.3, 0.5]
    train_frac: [0.3, 0.5]
