# config.yaml
# Base configuration
p: 113
depth: 1
epochs: 64_536

# Search space
search_space:
  latent_dim: [128, 256]
  lamb: [0.0, 0.5, 2.0]
  l2: [0.5, 1.0]
  dropout: [0.1, 0.2, 0.5]
  heads: [4, 8]
  lr: [0.0003, 0.001]
  train_frac: [0.3, 0.5]
