[tool.poetry]
name = "miiii"
version = "0.0.1"
description = "Mechanistic interpretability of irriducible integer identifiers"
authors = ["Noah Syrkis <desk@syrkis.com>"]
readme = "README.md"

[tool.poetry.scripts]
package_command = "main:main"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
oeis = "^2023.3.10"
tqdm = "^4.66.4"
requests = "^2.32.2"
einops = "^0.8.0"
matplotlib = "^3.9.0"
pyyaml = "^6.0.1"
jupyterlab = "^4.2.2"
optax = "^0.2.3"
jax-tqdm = "^0.2.2"
ipywidgets = "^8.1.5"
jax = "^0.4.35"
aim = "^3.25.0"
python-dotenv = "^1.0.1"
optuna = "^4.1.0"
jaxtyping = "^0.2.36"
equinox = "^0.11.11"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.3"
esch = { path = "../esch" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 120
