[tool.poetry]
name = "miiiii"
version = "0.0.0"
description = "Mechanistic interpretability of irriducible integer identifiers"
authors = ["Noah Syrkis <desk@syrkis.com>"]
readme = "README.md"

[tool.poetry.scripts]
package_command = "main:main"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
oeis = "^2023.3.10"
tqdm = "^4.66.4"
requests = "^2.32.2"
einops = "^0.8.0"
matplotlib = "^3.9.0"
pyyaml = "^6.0.1"
seaborn = "^0.13.2"
scikit-learn = "^1.5.0"
jupyterlab = "^4.2.2"
optax = "^0.2.3"
jaxtyping = "^0.2.33"
jax-tqdm = "^0.2.2"
ipywidgets = "^8.1.5"
esch = ">=0.2.5"
cairosvg = "^2.7.1"
jax = "^0.4.35"
wandb = "^0.18.5"
aim = "^3.25.0"
omegaconf = "^2.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-cov = "^5.0.0"
ruff = "^0.6.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# [tool.pytest.ini_options]
# minversion = "6.0"
# addopts = "--cov=miiiii --cov-report=term-missing"
# testpaths = ["test"]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 120
