wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.0
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1717613000
    t:
      1:
      - 5
      - 12
      - 53
      - 55
      2:
      - 5
      - 12
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 24
      4: 3.11.7
      5: 0.17.0
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
