# config.yaml
p: 37 #113
d: 64 # width
epochs: 65_536
dropout: 0.2
lr: 0.003
tick: 256
lamb: 0.5

# keep constant
l2: 1.0 # nanda
alpha: 0.98 # nanda
b1: 0.9 # nanda
b2: 0.98 # nanda
h: 4 # nanda
seed: 1 # whatever
