# config.yaml
device: "mac"

p: 113
d: 256
lr: 0.003
dropout: 0.2
lamb: 0.5
tick: 256
epochs: 65_536

# keep constant
l2: .1 # nanda
alpha: 0.98 # nanda
b1: 0.9 # nanda
b2: 0.98 # nanda
h: 4 # nanda
seed: 1 # whatever
